// apps/web/src/components/e2ee/E2EESetupModal.tsx
import { useState } from 'react';
import { toast } from 'sonner';
import { trpc } from '@/lib/trpc';
import { useE2EEStore } from '@/stores/e2eeStore';
import { setupUserKeys, type RecoveryKeyInfo } from '@onera/crypto';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ShieldCheck, AlertTriangle } from 'lucide-react';

type Step = 'password' | 'recovery' | 'confirm';

export function E2EESetupModal() {
  const { setStatus, setNeedsSetup, setError } = useE2EEStore();
  const createUserKeysMutation = trpc.userKeys.create.useMutation();

  const [step, setStep] = useState<Step>('password');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [recoveryInfo, setRecoveryInfo] = useState<RecoveryKeyInfo | null>(null);
  const [confirmInput, setConfirmInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSetupPassword = async (e: React.FormEvent) => {
    e.preventDefault();

    if (password !== confirmPassword) {
      toast.error('Passwords do not match');
      return;
    }

    if (password.length < 8) {
      toast.error('Password must be at least 8 characters');
      return;
    }

    setIsLoading(true);
    setStatus('unlocking');

    try {
      const { recoveryInfo: info, storableKeys } = await setupUserKeys(password);

      await createUserKeysMutation.mutateAsync({
        kekSalt: storableKeys.kekSalt,
        kekOpsLimit: storableKeys.kekOpsLimit,
        kekMemLimit: storableKeys.kekMemLimit,
        encryptedMasterKey: storableKeys.encryptedMasterKey,
        masterKeyNonce: storableKeys.masterKeyNonce,
        publicKey: storableKeys.publicKey,
        encryptedPrivateKey: storableKeys.encryptedPrivateKey,
        privateKeyNonce: storableKeys.privateKeyNonce,
        encryptedRecoveryKey: storableKeys.encryptedRecoveryKey,
        recoveryKeyNonce: storableKeys.recoveryKeyNonce,
        masterKeyRecovery: storableKeys.masterKeyRecovery,
        masterKeyRecoveryNonce: storableKeys.masterKeyRecoveryNonce,
      });

      setRecoveryInfo(info);
      setStep('recovery');
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to setup E2EE';
      setError(message);
      toast.error(message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleConfirmRecovery = (e: React.FormEvent) => {
    e.preventDefault();

    if (!recoveryInfo) return;

    const firstFourWords = recoveryInfo.mnemonic.split(' ').slice(0, 4).join(' ');
    if (confirmInput.toLowerCase().trim() !== firstFourWords.toLowerCase()) {
      toast.error('Please enter the first 4 words of your recovery phrase');
      return;
    }

    setNeedsSetup(false);
    setStatus('unlocked');
    toast.success('E2EE setup complete!');
  };

  return (
    <Dialog open>
      <DialogContent className="sm:max-w-md" onInteractOutside={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-primary" />
            Set Up E2EE
          </DialogTitle>
          <DialogDescription>
            {step === 'password' && 'Create a password to encrypt your chats.'}
            {step === 'recovery' && 'Save your recovery phrase securely.'}
            {step === 'confirm' && 'Confirm you\'ve saved your recovery phrase.'}
          </DialogDescription>
        </DialogHeader>

        {step === 'password' && (
          <form onSubmit={handleSetupPassword} className="space-y-4">
            <p className="text-sm text-muted-foreground">
              This password will be used to unlock your encryption on each device.
            </p>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                autoFocus
                autoComplete="new-password"
                minLength={8}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirm-password">Confirm Password</Label>
              <Input
                id="confirm-password"
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
                autoComplete="new-password"
                minLength={8}
              />
            </div>

            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? 'Setting up...' : 'Continue'}
            </Button>
          </form>
        )}

        {step === 'recovery' && recoveryInfo && (
          <div className="space-y-4">
            <Alert className="border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20">
              <AlertTriangle className="h-4 w-4 text-amber-600" />
              <AlertDescription className="text-amber-800 dark:text-amber-200">
                Write down these {recoveryInfo.wordCount} words and store them safely. You'll need them
                to recover your account if you forget your password.
              </AlertDescription>
            </Alert>

            <div className="p-4 bg-muted rounded-lg font-mono text-sm space-y-2">
              {recoveryInfo.formattedGroups.map((group, idx) => (
                <div key={idx} className="flex gap-4">
                  {group.map((word, wordIdx) => (
                    <span key={wordIdx} className="flex-1">
                      <span className="text-muted-foreground mr-1">{idx * 4 + wordIdx + 1}.</span>
                      {word}
                    </span>
                  ))}
                </div>
              ))}
            </div>

            <Button onClick={() => setStep('confirm')} className="w-full">
              I've saved my recovery phrase
            </Button>
          </div>
        )}

        {step === 'confirm' && recoveryInfo && (
          <form onSubmit={handleConfirmRecovery} className="space-y-4">
            <p className="text-sm text-muted-foreground">
              To confirm you've saved your recovery phrase, enter the first 4
              words below.
            </p>

            <div className="space-y-2">
              <Label htmlFor="confirm-words">First 4 words</Label>
              <Input
                id="confirm-words"
                type="text"
                value={confirmInput}
                onChange={(e) => setConfirmInput(e.target.value)}
                placeholder="Enter the first 4 words..."
                required
                autoFocus
              />
            </div>

            <div className="flex gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => setStep('recovery')}
              >
                Back
              </Button>
              <Button type="submit" className="flex-1">
                Confirm
              </Button>
            </div>
          </form>
        )}
      </DialogContent>
    </Dialog>
  );
}

// src/lib/components/e2ee/E2EESetupModal.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { setupUserKeys, formatMnemonicForDisplay, type RecoveryKeyInfo } from '$lib/crypto/sodium';
	import { useCreateUserKeysMutation } from '$lib/api/auth';

	interface Props {
		onclose: () => void;
	}

	let { onclose }: Props = $props();

	let step = $state<'passphrase' | 'recovery' | 'confirm'>('passphrase');
	let passphrase = $state('');
	let confirmPassphrase = $state('');
	let loading = $state(false);
	let recoveryInfo = $state<RecoveryKeyInfo | null>(null);
	let copiedRecovery = $state(false);

	const createKeysMutation = useCreateUserKeysMutation();

	async function handleSetup() {
		if (passphrase !== confirmPassphrase) {
			toast.error('Passphrases do not match');
			return;
		}

		if (passphrase.length < 8) {
			toast.error('Passphrase must be at least 8 characters');
			return;
		}

		loading = true;

		try {
			const result = await setupUserKeys(passphrase);
			recoveryInfo = result.recoveryInfo;

			// Save keys to server
			await $createKeysMutation.mutateAsync({
				kek_salt: result.storableKeys.kekSalt,
				kek_ops_limit: result.storableKeys.kekOpsLimit,
				kek_mem_limit: result.storableKeys.kekMemLimit,
				encrypted_master_key: result.storableKeys.encryptedMasterKey,
				master_key_nonce: result.storableKeys.masterKeyNonce,
				public_key: result.storableKeys.publicKey,
				encrypted_private_key: result.storableKeys.encryptedPrivateKey,
				private_key_nonce: result.storableKeys.privateKeyNonce,
				encrypted_recovery_key: result.storableKeys.encryptedRecoveryKey,
				recovery_key_nonce: result.storableKeys.recoveryKeyNonce,
				master_key_recovery: result.storableKeys.masterKeyRecovery,
				master_key_recovery_nonce: result.storableKeys.masterKeyRecoveryNonce
			});

			step = 'recovery';
		} catch (error) {
			toast.error(error instanceof Error ? error.message : 'Failed to setup E2EE');
		} finally {
			loading = false;
		}
	}

	function copyRecoveryPhrase() {
		if (recoveryInfo) {
			navigator.clipboard.writeText(recoveryInfo.mnemonic);
			copiedRecovery = true;
			toast.success('Recovery phrase copied');
			setTimeout(() => copiedRecovery = false, 2000);
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape' && step === 'passphrase') {
			onclose();
		}
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
	<div class="bg-slate-800 rounded-lg shadow-xl w-full max-w-md mx-4 p-6">
		{#if step === 'passphrase'}
			<div class="mb-6">
				<h2 class="text-xl font-semibold text-white mb-2">Set Up E2EE</h2>
				<p class="text-slate-400 text-sm">
					Create a passphrase to encrypt your chats. This is separate from your account password.
				</p>
			</div>

			<form onsubmit={(e) => { e.preventDefault(); handleSetup(); }} class="space-y-4">
				<div>
					<label for="passphrase" class="block text-sm font-medium text-slate-300 mb-1">
						Encryption Passphrase
					</label>
					<input
						type="password"
						id="passphrase"
						bind:value={passphrase}
						class="input"
						placeholder="Choose a strong passphrase"
						minlength="8"
						autofocus
					/>
				</div>

				<div>
					<label for="confirm" class="block text-sm font-medium text-slate-300 mb-1">
						Confirm Passphrase
					</label>
					<input
						type="password"
						id="confirm"
						bind:value={confirmPassphrase}
						class="input"
						placeholder="Confirm your passphrase"
					/>
				</div>

				<div class="flex gap-3">
					<button
						type="button"
						class="btn btn-secondary flex-1"
						onclick={onclose}
					>
						Cancel
					</button>
					<button
						type="submit"
						class="btn btn-primary flex-1"
						disabled={loading || !passphrase || !confirmPassphrase}
					>
						{#if loading}
							<svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
								<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none" />
								<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
							</svg>
						{/if}
						Set Up E2EE
					</button>
				</div>
			</form>
		{:else if step === 'recovery' && recoveryInfo}
			<div class="mb-6">
				<h2 class="text-xl font-semibold text-white mb-2">Save Your Recovery Phrase</h2>
				<p class="text-slate-400 text-sm">
					Write down these 24 words and keep them safe. This is the only way to recover your encrypted data if you forget your passphrase.
				</p>
			</div>

			<div class="bg-slate-900 rounded-lg p-4 mb-4">
				<div class="grid grid-cols-4 gap-2 text-sm">
					{#each recoveryInfo.formattedGroups as group, groupIndex}
						{#each group as word, wordIndex}
							<div class="flex items-center gap-1">
								<span class="text-slate-500 w-5 text-right">{groupIndex * 4 + wordIndex + 1}.</span>
								<span class="text-white font-mono">{word}</span>
							</div>
						{/each}
					{/each}
				</div>
			</div>

			<button
				class="btn btn-secondary w-full mb-4"
				onclick={copyRecoveryPhrase}
			>
				{copiedRecovery ? 'Copied!' : 'Copy to Clipboard'}
			</button>

			<div class="bg-amber-900/30 border border-amber-700 rounded-lg p-3 mb-4">
				<p class="text-amber-200 text-sm">
					<strong>Warning:</strong> Never share this phrase. Anyone with it can access your encrypted data.
				</p>
			</div>

			<button
				class="btn btn-primary w-full"
				onclick={() => step = 'confirm'}
			>
				I've Saved My Recovery Phrase
			</button>
		{:else if step === 'confirm'}
			<div class="text-center">
				<div class="mb-4">
					<svg class="w-16 h-16 mx-auto text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
					</svg>
				</div>
				<h2 class="text-xl font-semibold text-white mb-2">E2EE Set Up Successfully!</h2>
				<p class="text-slate-400 text-sm mb-6">
					Your encryption is now active. All your chats will be encrypted end-to-end.
				</p>
				<button
					class="btn btn-primary w-full"
					onclick={onclose}
				>
					Start Chatting
				</button>
			</div>
		{/if}
	</div>
</div>
